"use client";

import React from "react";
import Link from "next/link";
import { VirtualFile } from "@/lib/developer/types";
import { ProjectDetails, BuildPlan } from "@/lib/types";
import { cn } from "@/lib/utils";
import {
  FileCode,
  Sparkles,
  Bot,
  ArrowRight,
  CheckCircle2,
  AlertCircle,
  HelpCircle,
  Cpu,
  Workflow,
} from "lucide-react";

interface DeveloperContextPanelProps {
  activeFile: VirtualFile | null;
  project: ProjectDetails;
  currentPlan?: BuildPlan | null;
}

export function DeveloperContextPanel({
  activeFile,
  project,
  currentPlan,
}: DeveloperContextPanelProps) {
  const getAgentLabel = (role?: VirtualFile["agentRole"]) => {
    switch (role) {
      case "frontend":
        return { name: "Frontend Agent", color: "text-[#38BDF8]", bg: "bg-[#38BDF8]/10 border-[#38BDF8]/30" };
      case "backend":
        return { name: "Backend Agent", color: "text-[#3FB950]", bg: "bg-[#3FB950]/10 border-[#3FB950]/30" };
      case "qa":
        return { name: "QA Validation Agent", color: "text-[#F59E0B]", bg: "bg-[#F59E0B]/10 border-[#F59E0B]/30" };
      case "architect":
      default:
        return { name: "Architect Swarm", color: "text-[#A855F7]", bg: "bg-[#A855F7]/10 border-[#A855F7]/30" };
    }
  };

  const agentInfo = getAgentLabel(activeFile?.agentRole);

  return (
    <aside className="h-full flex flex-col bg-[#0E1117] border-l border-[#21262D] select-none overflow-y-auto no-scrollbar font-mono text-xs">
      {/* Panel Header */}
      <div className="h-9 px-3 border-b border-[#21262D] flex items-center justify-between text-[#8B949E] shrink-0">
        <span className="uppercase text-[10px] font-semibold tracking-wider text-[#6E7681]">
          Architect Context
        </span>
        <div className="flex items-center gap-1 text-[11px] text-[#00F2FE]">
          <Cpu className="h-3 w-3 animate-pulse" />
          <span>Sync Active</span>
        </div>
      </div>

      <div className="p-3 space-y-4">
        {/* CURRENT FILE SECTION */}
        <section className="space-y-2">
          <div className="text-[10px] uppercase tracking-wider text-[#6E7681] font-semibold flex items-center gap-1.5">
            <FileCode className="h-3 w-3 text-[#00F2FE]" />
            <span>Current File</span>
          </div>

          {activeFile ? (
            <div className="p-2.5 rounded-lg bg-[#161B22] border border-[#21262D] space-y-2">
              <div className="flex items-start justify-between gap-2">
                <span className="font-semibold text-white truncate text-xs">
                  {activeFile.name}
                </span>
                <span className="text-[10px] px-1.5 py-0.5 rounded uppercase font-semibold bg-[#21262D] text-[#8B949E]">
                  {activeFile.language}
                </span>
              </div>

              <div className="text-[11px] text-[#8B949E] break-all">
                {activeFile.path}
              </div>

              <div className="pt-1 border-t border-[#21262D] flex items-center justify-between text-[11px]">
                <span className="text-[#6E7681]">Status</span>
                {activeFile.isModified ? (
                  <span className="flex items-center gap-1 text-[#F59E0B]">
                    <AlertCircle className="h-3 w-3" />
                    Unsaved
                  </span>
                ) : (
                  <span className="flex items-center gap-1 text-[#3FB950]">
                    <CheckCircle2 className="h-3 w-3" />
                    Clean
                  </span>
                )}
              </div>
            </div>
          ) : (
            <div className="p-3 rounded-lg bg-[#161B22]/50 border border-[#21262D] text-[#6E7681] text-center text-xs">
              No file currently active
            </div>
          )}
        </section>

        {/* AI CONTEXT SECTION */}
        <section className="space-y-2">
          <div className="text-[10px] uppercase tracking-wider text-[#6E7681] font-semibold flex items-center gap-1.5">
            <Bot className="h-3 w-3 text-[#A855F7]" />
            <span>AI Origin & Attribution</span>
          </div>

          <div className="p-2.5 rounded-lg bg-[#161B22] border border-[#21262D] space-y-2.5">
            <div>
              <div className="text-[10px] text-[#6E7681] uppercase mb-0.5">
                Related Build Step
              </div>
              <div className="text-white text-xs font-sans leading-tight">
                {activeFile?.relatedBuildStep || "Core System Setup & Workspace Architecture"}
              </div>
            </div>

            <div>
              <div className="text-[10px] text-[#6E7681] uppercase mb-1">
                Generated By
              </div>
              <div className={cn("inline-flex items-center gap-1.5 px-2 py-0.5 rounded text-[11px] font-medium border", agentInfo.bg, agentInfo.color)}>
                <Bot className="h-3 w-3" />
                <span>{agentInfo.name}</span>
              </div>
            </div>

            <div>
              <div className="text-[10px] text-[#6E7681] uppercase mb-0.5">
                Target Project
              </div>
              <div className="text-[#C9D1D9] text-xs truncate">
                {project.name}
              </div>
            </div>

            {currentPlan && (
              <div className="pt-2 border-t border-[#21262D]">
                <div className="text-[10px] text-[#6E7681] uppercase mb-0.5">
                  Active Build Plan
                </div>
                <div className="text-[#38BDF8] text-[11px] font-sans truncate" title={currentPlan.title}>
                  {currentPlan.title}
                </div>
              </div>
            )}
          </div>
        </section>

        {/* ASK ARCHITECT ACTION */}
        <section className="pt-2">
          <div className="p-3 rounded-lg bg-gradient-to-br from-[#A855F7]/10 via-[#00F2FE]/5 to-transparent border border-[#A855F7]/30 space-y-2.5">
            <div className="flex items-center gap-1.5 text-white font-semibold text-xs">
              <Sparkles className="h-3.5 w-3.5 text-[#00F2FE]" />
              <span>Need Modifications?</span>
            </div>
            <p className="text-[11px] text-[#8B949E] leading-relaxed font-sans">
              Switch back to Build Mode to guide Architect with natural language instructions or plan enhancements.
            </p>

            <Link
              href={`/projects/${project.id}?mode=build${activeFile ? `&file=${encodeURIComponent(activeFile.path)}` : ""}`}
              className="inline-flex items-center justify-between w-full px-3 py-1.5 rounded-md bg-[#A855F7]/20 hover:bg-[#A855F7]/30 text-white border border-[#A855F7]/40 text-xs font-semibold transition-colors group"
            >
              <span className="flex items-center gap-1.5">
                <Workflow className="h-3.5 w-3.5 text-[#00F2FE]" />
                Ask Architect
              </span>
              <ArrowRight className="h-3 w-3 text-[#A855F7] group-hover:translate-x-0.5 transition-transform" />
            </Link>
          </div>
        </section>

        {/* WORKSPACE HINT */}
        <div className="p-2.5 rounded-lg bg-[#161B22]/40 border border-[#21262D] text-[10px] text-[#6E7681] space-y-1">
          <div className="flex items-center gap-1 font-semibold text-[#8B949E]">
            <HelpCircle className="h-3 w-3 text-[#00F2FE]" />
            <span>Developer Mode Guide</span>
          </div>
          <p className="leading-normal font-sans">
            Direct file edits remain synced with the project context. Use terminal below to test simulated builds and run tests.
          </p>
        </div>
      </div>
    </aside>
  );
}
